config/routes.rb
Rails.application.routes.draw do
  root 'courts#index'
  get '/search', to: 'courts#search'
  get '/user_create', to: 'users#new'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :courts
  get '/court_create', to: 'courts#new'
  post '/courts', to: 'courts#create'
  post '/guest_login', to: 'guest_sessions#create'
  resources :contacts
  resources :courts do
    resources :comments, only: %i[create destroy]
    resources :favorites, only: %i[create destroy]
  end
  resources :tags do
    get 'courts', to: 'courts#tagsearch'
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :follow_relationships, only: %i[create destroy]

  namespace :api, { format: 'json' } do
    namespace :v1 do
      get '/login', to: 'sessions#new'
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
      get '/user_create', to: 'users#new'
      get '/favorite_court/:id', to: 'users#favorite_court'
      get '/post_court/:id', to: 'users#post_court'
      get '/court_count/:id', to: 'users#court_count'
      # get '/courts/search/:location/:keyword', to: 'courts#search'
      get '/courts/search/:location', to: 'courts#search'
      resources :users
      resources :courts
      get '/court_create', to: 'courts#new'
      post '/courts', to: 'courts#create'
      get '/contact_create', to: 'contacts#new'
      post '/contacts', to: 'contacts#create'
      get '/taglist', to: 'courts#taglist'
      get '/court_rank', to: 'courts#court_rank'
      get '/latest_court', to: 'courts#latest_court'
      get '/court_tag/:id', to: 'courts#court_tag'
      get '/favorite_count/:id', to: 'favorites#favorite_count'
      get '/tagsearch/:id', to: 'courts#tagsearch'
      get '/comment_count/:id', to: 'comments#comment_count'
      get '/court_comment/:id', to: 'courts#court_comment'
      delete '/court/:court_id/user/:user_id/favorite', to: 'favorites#destroy'
      delete '/court/:court_id/user/:user_id/comment', to: 'comments#destroy'
      get '/court/:court_id/user/:user_id/favorite', to: 'favorites#show'
      get '/follower/:follower_id/following/:following_id/follow', to: 'follow_relationships#show'
      delete '/follower/:follower_id/following/:following_id/unfollow', to: 'follow_relationships#destroy'
      get '/follow_count/:id', to: 'follow_relationships#follow_count'
      get '/follower_count/:id', to: 'follow_relationships#follower_count'
      resources :courts do
        resources :comments, only: %i[create destroy]
        resources :favorites, only: %i[create]
      end
      resources :contacts
      resources :follow_relationships, only: %i[create]
      resources :users do
        member do
          get :following, :followers
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :courts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'FollowRelationship', dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'FollowRelationship', dependent: :destroy
  has_many :followers, through: :follower_relationships
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  mount_uploader :image, ImageUploader
  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def already_liked?(court)
    favorites.exists?(court_id: court.id)
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def follow(other_user)
    self.following_relationships.create(following_id: other_user.id)
  end

  def unfollow(other_user)
    self.following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  before_action :set_user, only: %i[show]
  wrap_parameters :user, include: [:name, :email, :password, :password_confirmation, :image]

  def new
    user = User.new
  end

  def index
    users = User.all.page(params[:page]).per(12)
    render json: users
  end

  def court_count
    court_count = Court.where(user_id: params[:id]).count
    render json: court_count
  end

  def show
    # user = User.find(params[:id])
    # @courts = @user.courts.page(params[:page]).per(3)
    # favorites = Favorite.where(user_id: @user.id).order(created_at: :desc).pluck(:court_id)
    # @favorites = Court.page(params[:page]).per(3).find(favorites)
    # render json: @user.as_json(include: :court)
    render json: @user
  end

  def favorite_court
    user = User.find(params[:id])
    favorites = Favorite.where(user_id: user.id).order(created_at: :desc).pluck(:court_id)
    favorite_court = Court.page(params[:page]).per(3).find(favorites)
    render json: favorite_court.as_json(include: :user)
  end

  def post_court
    user = User.find(params[:id])
    post_court = user.courts.page(params[:page]).per(3)
    render json: post_court.as_json(include: :user)
  end

  def create
    user = User.new(user_params)
    user.image = "default.jpg"
    if user.save
      # log_in @user
      # flash[:success] = 'テニスコートサーチにようこそ！'
      # redirect_back_or @user
      render json: user
    else
      render json: { message: '登録できませんでした'}
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:success] = 'アカウント情報を更新しました。'
      redirect_to uuser
    else
      render json: { message: 'ユーザー更新できませんでした'}
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    render json: { status: "SUCCESS", message: "ユーザー情報は削除されました", data: user }
  end

  def following
    user = User.find(params[:id])
    users = user.followings.page(params[:page]).per(12)
    render json: users
  end

  def followers
    user = User.find(params[:id])
    users = user.followers.page(params[:page]).per(12)
    render json: users
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update destroy]
  before_action :correct_user,   only: %i[edit update]

  def new
    @user = User.new
  end

  def index
    @users = User.all.page(params[:page]).per(12)
  end

  def show
    @user = User.find(params[:id])
    @courts = @user.courts.page(params[:page]).per(3)
    favorites = Favorite.where(user_id: @user.id).order(created_at: :desc).pluck(:court_id)
    @favorites = Court.page(params[:page]).per(3).find(favorites)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'テニスコートサーチにようこそ！'
      redirect_back_or @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'アカウント情報を更新しました。'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'アカウントを削除しました。'
    redirect_to root_url
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings.page(params[:page]).per(12)
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(12)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.following_relationships.build) do |f| %>
  <%= f.hidden_field :following_id, value: @user.id %>
  <%= f.submit "フォロー", class: "inline-block text-gray-100 bg-yellow-400 border border-yellow-400 hover:text-yellow-500 hover:bg-white font-base px-4 py-2 rounded text-base" %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :image, "プロフィール画像", {class: "text-lg font-bold"} %>
  <% if @user.image? %>
    <%= image_tag @user.image.url, size: '150x150', class: 'border-2' %>
  <% else %>
    <%= image_tag asset_path("default.jpg"), size: '150x150', class: 'border-2' %>
  <% end %>
  <%= f.file_field :image, class: "btn btn-sm my-2 btn-outline-secondary rounded-pill mr-8", accept: 'image/jpeg,image/gif,image/png' %>

  <%= f.label :name, "ニックネーム", {class: "text-lg font-bold"} %>
  <%= f.text_field :name, class: "mb-4 form-control", placeholder: '30文字以内で入力してください。' %>

  <%= f.label :email, "メールアドレス", {class: "text-lg font-bold"} %>
  <%= f.email_field :email, class: "form-control mb-4", placeholder: 'メールアドレスを入力してください。' %>

  <%= f.label :password, "パスワード", {class: "text-lg font-bold"} %>
  <%= f.password_field :password, class: "mb-4 form-control", placeholder: '半角英数字6文字以上' %>

  <%= f.label :password_confirmation, "パスワード(確認用)", {class: "text-lg font-bold"} %>
  <%= f.password_field :password_confirmation, class: "form-control mb-4", placeholder: '半角英数字6文字以上' %>

  <div class="text-center my-4">
    <%= f.submit yield(:button_text), class: "inline-block text-gray-100 bg-green-500 border border-yellow-500 hover:text-green-500 hover:bg-white font-base px-4 py-2 rounded text-base" %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.following_relationships.find_by(following_id: @user.id),method: :delete) do |f| %>
  <%= f.hidden_field :following_id %>  
  <%= f.submit "フォロー解除", class: "inline-block text-gray-100 bg-red-500 border border-yellow-500 hover:text-red-500 hover:bg-white font-base px-4 py-2 rounded text-base" %>
<% end %>

app/views/users/_user_index.html.erb
<% if @users.present? %>
  <ul class="mb-2 mx-auto grid gap-x-2 gap-y-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% @users.each do |user| %>
      <li class="mt-2 mx-auto bg-green-100 hover:bg-white border-2 border-gray-300 px-4 pt-2 list-none hover:shadow card">
        <% if user.image? %>
          <%= link_to image_tag(user.image.url), user, size: "200x200" %>
        <% else %>
          <%= link_to image_tag(asset_path("default.jpg")), user, class: "border-1 border-black", size: "200x200" %>
        <% end %>
        <div class="text-center">
          <p class="font-bold underline mt-2"><%= link_to user.name, user_path(user), class: "hover:text-green-600"%></p>
          <p class="text-xl h-6 mt-1">投稿数：<%= user.courts.count %></p>
        </div>
        <div>
          <% if logged_in? && (current_user == user or current_user.admin) %>
            <div class="text-center my-2">
              <%= link_to user, method: :delete, data: { confirm: "削除してもよろしいですか?" } do %>
                <p class="inline-block text-red-500 bg-gray-100 border-2 hover:text-gray-100 hover:bg-red-500 hover:shadow font-base px-4 py-2 rounded text-base">ユーザー削除</p>
              <% end %>
            </div>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="text-center">
      <p class="text-lg sm:text-2xl ">該当するユーザーはおりません。</p>
    </div>
<% end %>
<%= paginate @users %>

app/views/users/edit.html.erb
<% provide(:button_text, '変更') %>
<div class="container py-4 ">
  <div class="py-2 user-form mx-auto  border-2 bg-white shadow-md">
    <h1 class="text-2xl sm:text-3xl text-center py-4 font-bold">ユーザー情報変更</h1>
    <div class="form-wide mx-auto">
      <%= render 'form' %>
      <div class="text-center my-2">
        <%= link_to @user, method: :delete, data: { confirm: "削除してもよろしいですか?" } do %>
          <p class="inline-block text-red-500 bg-gray-100 border-2 hover:text-gray-100 hover:bg-red-500 hover:shadow font-base px-4 py-2 rounded text-base">ユーザー削除</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container pb-4">
  <div class="text-center">
    <h1 class="text-2xl sm:text-3xl text-center py-4">フォロワー一覧</h1>
  </div>
  <%= render "user_index" %>
</div>

app/views/users/following.html.erb
<div class="container pb-4">
  <div class="text-center">
    <h1 class="text-2xl sm:text-3xl text-center py-4">フォロー一覧</h1>
  </div>
  <%= render "user_index" %>
</div>

app/views/users/index.html.erb
<div class="container pb-4">
  <div class="text-center">
    <h1 class="text-2xl sm:text-3xl text-center py-4">ユーザー一覧</h1>
  </div>
  <%= render "user_index" %>
</div>

app/views/users/new.html.erb
<% provide(:button_text, 'ユーザー作成') %>

<div class="container py-4">
  <div class="py-2 user-form mx-auto  border-2 bg-white shadow-md">
    <h1 class="text-2xl sm:text-3xl text-center py-4 font-bold">新規登録</h1>
    <div class="form-wide mx-auto">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="grid lg:grid-cols-4">
  <div class="user-info col-span-1 container mx-auto my-auto w-64">
    <div class="user-image justify-items-center mt-6 w-64 justify-center">
      <% if @user.image? %>
        <%= link_to image_tag(@user.image.url), @user, :size => '200x200', class: "w-full h-40 mx-auto items-start" %>
      <% else %>
        <%= link_to image_tag(asset_path("default.jpg")), @user, :size => '200x200', class: "w-full h-40 mx-auto items-start" %>
      <% end %>
      <div class="text-center text-gray-700 text-xl font-bold mt-3">
        <%= @user.name %>さんのマイページ
      </div>
      <div class="text-center">
        <p class="text-xl h-6 mt-1">投稿数：<%= @user.courts.count %></p>
        </div>
      <div class="text-center my-2 flex">
        <%= link_to "フォロー#{@user.followings.count}", following_user_path(@user), class: "text-gray-100 bg-indigo-500 border border-yellow-500 hover:text-indigo-400 hover:bg-white font-base rounded px-3 py-2 text-base mx-2" %>
        <%= link_to "フォロワー#{@user.followers.count}", followers_user_path(@user), class: "text-gray-100 bg-indigo-500 border border-yellow-500 hover:text-indigo-400 hover:bg-white font-base rounded px-2 py-2 text-base mx-2" %>
      </div>
      <% if logged_in? && @user != current_user%>
        <div id="follow_form" class="text-center my-3">
          <% if current_user.following?(@user) %>
            <%= render "unfollow" %>
          <% else %>
            <%= render "follow" %>
          <% end %>
        </div>
      <% end %>
      <% if current_user == @user %>
        <div class="text-center my-2">
          <%= link_to 'ユーザー情報編集', edit_user_path(current_user), class: "inline-block text-gray-100 bg-green-500 border border-yellow-500 hover:text-green-500 hover:bg-white font-base px-4 py-2 rounded text-base" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="lg:col-span-3 mb-4 lg:mt-4">
    <h2 class="text-2xl text-center font-bold mb-4">お気に入りコート</h2>
    <% if @favorites.present? %>
      <ul class="mb-2 mx-auto grid gap-x-2 gap-y-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3">        
        <% @favorites.each do |court| %>
          <%= render partial: "courts/court", locals: { court: court } %>
        <% end %>
      </ul>
    <% else %>
      <p class="text-lg sm:text-2xl text-center">該当のコートはありません。</p>
    <% end %>
    <h2 class="text-2xl text-center font-bold my-3">投稿したコート</h2>
    <% if @courts.present? %>
      <ul class="mb-2 mx-auto grid gap-x-2 gap-y-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3">        
        <% @courts.each do |court| %>
          <%= render partial: "courts/court", locals: { court: court } %>
        <% end %>
      </ul>
    <% else %>
      <p class="text-lg sm:text-2xl text-center">該当のコートはありません。</p>
    <% end %>
    <%= paginate @courts %>
  </div>
</div>