config/routes.rb
Rails.application.routes.draw do
  root 'courts#index'
  get '/search', to: 'courts#search'
  get '/user_create', to: 'users#new'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :courts
  get '/court_create', to: 'courts#new'
  post '/courts', to: 'courts#create'
  post '/guest_login', to: 'guest_sessions#create'
  resources :contacts
  resources :courts do
    resources :comments, only: %i[create destroy]
    resources :favorites, only: %i[create destroy]
  end
  resources :tags do
    get 'courts', to: 'courts#tagsearch'
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :follow_relationships, only: %i[create destroy]

  namespace :api, { format: 'json' } do
    namespace :v1 do
      get '/login', to: 'sessions#new'
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
      get '/user_create', to: 'users#new'
      get '/favorite_court/:id', to: 'users#favorite_court'
      get '/post_court/:id', to: 'users#post_court'
      get '/court_count/:id', to: 'users#court_count'
      # get '/courts/search/:location/:keyword', to: 'courts#search'
      get '/courts/search/:location', to: 'courts#search'
      resources :users
      resources :courts
      get '/court_create', to: 'courts#new'
      post '/courts', to: 'courts#create'
      get '/contact_create', to: 'contacts#new'
      post '/contacts', to: 'contacts#create'
      get '/taglist', to: 'courts#taglist'
      get '/court_rank', to: 'courts#court_rank'
      get '/latest_court', to: 'courts#latest_court'
      get '/court_tag/:id', to: 'courts#court_tag'
      get '/favorite_count/:id', to: 'favorites#favorite_count'
      get '/tagsearch/:id', to: 'courts#tagsearch'
      get '/comment_count/:id', to: 'comments#comment_count'
      get '/court_comment/:id', to: 'courts#court_comment'
      delete '/court/:court_id/user/:user_id/favorite', to: 'favorites#destroy'
      delete '/court/:court_id/user/:user_id/comment', to: 'comments#destroy'
      get '/court/:court_id/user/:user_id/favorite', to: 'favorites#show'
      get '/follower/:follower_id/following/:following_id/follow', to: 'follow_relationships#show'
      delete '/follower/:follower_id/following/:following_id/unfollow', to: 'follow_relationships#destroy'
      get '/follow_count/:id', to: 'follow_relationships#follow_count'
      get '/follower_count/:id', to: 'follow_relationships#follower_count'
      resources :courts do
        resources :comments, only: %i[create destroy]
        resources :favorites, only: %i[create]
      end
      resources :contacts
      resources :follow_relationships, only: %i[create]
      resources :users do
        member do
          get :following, :followers
        end
      end
    end
  end
end

app/models/court.rb
class Court < ApplicationRecord
  geocoded_by :address
  before_validation :geocode
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  mount_uploader :image, ImageUploader
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :price, presence: true, length: { maximum: 10 }
  validates :number, presence: true, length: { maximum: 10 }
  validates :latitude, presence: true, uniqueness: true
  validates :longitude, presence: true, uniqueness: true
  validates :reserve, presence: true
  validates :remarks, length: { maximum: 200 }

  class << self
    def within_box(distance, latitude, longitude)
      @distance = distance
      center_point = [latitude, longitude]
      box = Geocoder::Calculations.bounding_box(center_point, @distance)
      self.within_bounding_box(box)
    end
  end
  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end
    new_tags.each do |new|
      court_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << court_tag
    end
  end
end

app/controllers/api/v1/courts_controller.rb
class Api::V1::CourtsController < ApiController
  # before_action :logged_in_user, only: %i[destroy]
  wrap_parameters :court, include: [:name, :tag_name, :address, :latitude, :longitude, :price, :image, :number, :remarks, :reserve, :user_id]

  def new
    court = Court.new
  end

  def court_tag
    court = Court.find(params[:id])
    court_tags = court.tags
    render json: court_tags
  end

  def show
    court = Court.find(params[:id])
    # gon.court = court
    render json: court.as_json(include: :user)
    # @court_tags = @court.tags
    # @comment = Comment.new
    # @comments = @court.comments.includes(:user).page(params[:page])
    # @favorite = Favorite.new
  end

  def court_comment
    court = Court.find(params[:id])
    court_comment = court.comments.includes(:user).page(params[:page])
    render json: court_comment.as_json(include: :user)
  end

  def taglist
    taglist = Tag.all.page(params[:page])
    render json: taglist
  end

  def court_rank
    court_rank = Court.includes(:user).unscope(:order).find(Favorite.group(:court_id).order('count(court_id) desc').limit(4).pluck(:court_id))

    render json: court_rank.as_json(include: :user)
  end

  def latest_court
    latest_court = Court.includes(:user).order(created_at: :desc).limit(4)
    render json: latest_court.as_json(include: :user)
  end

  def index
    # @tag_list = Tag.all.page(params[:page])
    courts = Court.all.page(params[:page]).per(12)
    render json: courts.as_json(include: :user)
    # all_ranks = Court.includes(:user).unscope(:order).find(Favorite.group(:court_id).order('count(court_id) desc').limit(4).pluck(:court_id))
    # latest_courts = Court.includes(:user).order(created_at: :desc).limit(4)
    
    # render json: {latest_courts: latest_courts, all_ranks: all_ranks}
    
    # jsonHash = [ all_ranks, latest_courts ]

    # render json: jsonHash
    
  end

  def search
    # @tag_list = Tag.all
    results = Geocoder.search(params[:location])
    if results.empty?
      render json: { message: 'コート情報を取得できませんでした'}
    else
      selection = params[:keyword]
      latitude = results.first.coordinates[0]
      longitude = results.first.coordinates[1]
      courts = Court.within_box(20, latitude, longitude)
      # search_courts = case selection
      #           when 'near'
      #             Court.near(results.first.coordinates, 20).page(params[:page]).per(12)
      #           when 'inexpensive'
      #             courts.order(price: :asc).page(params[:page]).per(12)
      #           when 'number'
      #             courts.order(number: :desc).page(params[:page]).per(12)
      #           else
      #             courts.page(params[:page]).per(12)
      #           end
      search_courts = courts.page(params[:page]).per(12)
      render json: search_courts.as_json(include: :user)
    end
  end

  def tagsearch
    tag = Tag.find(params[:id])
    courts = tag.courts.all.page(params[:page]).per(12)

    render json: courts.as_json(include: :user)
  end

  def edit
    court = Court.find(params[:id])
  end

  def create
    court = Court.new(court_params)
    tag_list = params[:court][:tag_name].split(nil)
    if court.save!
      court.save_tag(tag_list)
      # flash[:success] = 'コート情報を受け付けました！'
      # redirect_to @court
      render json: court
    else
      render json: { message: 'コート投稿出来ませんでした'}
    end
  end

  def update
    court = Court.find(params[:id])
    # tag_list = params[:court][:tag_name].split(nil)
    if court.update(court_params)
      # @court.save_tag(tag_list)
      # flash[:success] = 'アカウント情報を更新しました。'
      # redirect_to @court
      render json: court
    else
      render json: { message: 'コート投稿出来ませんでした'}
    end
  end

  def destroy
    court = Court.find(params[:id])
    court.destroy
    render json: { status: "SUCCESS", message: "コート情報は削除されました", data: court }
  end

  private

  def court_params
    params.require(:court).permit(:name, :address, :price, :hour, :image, :number, :remarks, :latitude, :longitude, :reserve, :user_id)
  end

  def logged_in_user
    unless logged_in?
      store_location
      # flash[:danger] = 'ログインをお願いします。'
      redirect_to login_url
    end
  end

  def permit_update_delete
    @court = Court.find(params[:id])
    unless (@court.user_id == current_user.id) || current_user.admin
      flash[:notice] = '投稿者以外の編集・削除はできません。'
      redirect_to root_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :logged_in_user, only: %i[edit create destroy]
  before_action :permit_update_delete, only: [:edit]

  def new
    @court = Court.new
  end

  def show
    @court = Court.find(params[:id])
    @court_tags = @court.tags
    gon.court = @court
    @comment = Comment.new
    @comments = @court.comments.includes(:user).page(params[:page])
    @favorite = Favorite.new
  end

  def index
    @tag_list = Tag.all.page(params[:page])
    @courts = Court.all.page(params[:page])
    @all_ranks = Court.includes(:user).unscope(:order).find(Favorite.group(:court_id).order('count(court_id) desc').limit(4).pluck(:court_id))
    @latest_courts = Court.includes(:user).order(created_at: :desc).limit(4)
  end

  def search
    @tag_list = Tag.all
    results = Geocoder.search(params[:location])
    if results.empty?
      flash[:danger] = '検索結果は見つかりませんでした。'
      redirect_to root_path
    else
      selection = params[:keyword]
      latitude = results.first.coordinates[0]
      longitude = results.first.coordinates[1]
      courts = Court.within_box(20, latitude, longitude)
      @courts = case selection
                when 'near'
                  Court.near(results.first.coordinates, 20).page(params[:page]).per(12)
                when 'inexpensive'
                  courts.order(price: :asc).page(params[:page]).per(12)
                when 'number'
                  courts.order(number: :desc).page(params[:page]).per(12)
                else
                  courts.page(params[:page]).per(12)
                end
    end
  end

  def tagsearch
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @tag_court_lists = @tag.courts.all.page(params[:page]).per(12)
  end

  def edit
    @court = Court.find(params[:id])
  end

  def create
    @court = current_user.courts.new(court_params)
    tag_list = params[:court][:tag_name].split(nil)
    if @court.save
      @court.save_tag(tag_list)
      flash[:success] = 'コート情報を受け付けました！'
      redirect_to @court
    else
      render 'new'
    end
  end

  def update
    @court = Court.find(params[:id])
    tag_list = params[:court][:tag_name].split(nil)
    if @court.update(court_params)
      @court.save_tag(tag_list)
      flash[:success] = 'アカウント情報を更新しました。'
      redirect_to @court
    else
      render 'edit'
    end
  end

  def destroy
    Court.find(params[:id]).destroy
    flash[:success] = 'コート情報を削除しました。'
    redirect_to root_url
  end

  private

  def court_params
    params.require(:court).permit(:name, :address, :price, :hour, :image, :number, :remarks, :latitude, :longitude, :reserve)
  end

  def logged_in_user
    unless logged_in?
      store_location
      # flash[:danger] = 'ログインをお願いします。'
      redirect_to login_url
    end
  end

  def permit_update_delete
    @court = Court.find(params[:id])
    unless (@court.user_id == current_user.id) || current_user.admin
      flash[:notice] = '投稿者以外の編集・削除はできません。'
      redirect_to root_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/views/courts/_court.html.erb
<li class="bg-green-100 mx-auto hover:bg-white border-2 border-gray-300 px-4 pt-2 list-none hover:shadow card">
  <% if court.image? %>
    <%= link_to image_tag(court.image.url), court, size: "200x200" %>
  <% else %>
    <%= link_to image_tag(asset_path("default_court.png")), court, size: "200x200" %>
  <% end %>
  <div class="text-center">
    <p class="font-bold underline mt-2"><%= link_to court.name, court_path(court), class: "hover:text-green-600"%></p>
    <p class="text-xl h-6 mt-1">料金：<%= court.price %>円/時間</p>
    <div class="mt-2">
      <span><i class="fas fa-star fa-lg fill-current text-yellow-500"></i><%= court.favorites.count %></span>
      <span class="font-bold underline ml-6"><i class="far fa-user mr-2"></i><%= link_to court.user.name, user_path(court.user), class: "hover:text-green-600" %></span>
    </div>
    <p class="text-xl h-6 mt-1">コート数：<%= court.number %>面</p>
  </div>
</li>

app/views/courts/_form.html.erb
<%= form_with(model: @court, local: true) do |f| %>
  <%= render 'shared/court_error_messages' %>

  <%= f.label :image, "施設画像", {class: "text-lg font-bold"} %>
  <% if @court.image? %>
    <%= image_tag @court.image.url, size: '150x150', class: 'border-2' %>
  <% else %>
    <%= image_tag asset_path("default_court.png"), size: '150x150', class: 'border-2' %>
  <% end %>
  <%= f.file_field :image, class: "btn btn-sm my-2 btn-outline-secondary rounded-pill mr-8", accept: 'image/jpeg,image/gif,image/png' %>

  <%= f.label :name, "施設名(テニスコート名)", {class: "text-lg font-bold"} %>
  <%= f.text_field :name, class: "mb-3 form-control", placeholder: '施設名を入力してください。' %>

  <%= f.label :address, "住所", {class: "text-lg font-bold"} %>
  <%= f.text_field :address, class: "mb-3 form-control", placeholder: '住所を入力してください。' %>

  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>

  <%= f.label :price, "1時間あたりの料金", {class: "text-lg font-bold"} %>
  <%= f.number_field :price, class: "mb-3 form-control", placeholder: '数字を入力してください。' %>

  <%= f.label :number, "コート数", {class: "text-lg font-bold"} %>
  <%= f.number_field :number, class: "mb-3 form-control", placeholder: 'コート数を入力してください。' %>

  <%= f.label :reserve, "予約URL", {class: "text-lg font-bold"} %>
  <%= f.text_field :reserve, class: "mb-3 form-control", placeholder: '予約URLを貼り付けてください。' %>

  <%= f.label :tag_name, "タグ付け(半角スペースで複数可能)", {class: "text-lg font-bold"} %>
  <%= f.text_field :tag_name, class: "mb-3 form-control", placeholder: '例：オムニ 埼玉 クレー' %>

  <%= f.label :remarks, "備考", {class: "text-lg font-bold"} %>
  <%= f.text_field :remarks, class: "mb-3 form-control", placeholder: '他に何かあればご記入下さい。' %>

  <div class="text-center my-4">
    <%= f.submit yield(:button_text), class: "inline-block text-gray-100 bg-green-500 border border-yellow-500 hover:text-green-500 hover:bg-white font-base px-4 py-2 rounded text-base" %>
  </div>
<% end %>

app/views/courts/_search_form.html.erb
<div class="text-center">
  <h2 class="text-3xl pt-3">テニスコート検索</h2>
  <h3 class="text-2xl m-1 border-b-2 border-black">〜最適なテニスコートをあなたへ〜</h3>
  <div class="mt-3">
    <h2 class="text-2xl">タグリスト</h3>
    <% if @tag_list.present? %>
      <% @tag_list.each do |tag| %>
        <span class="inline-block my-2 px-3 py-1 border-2 border-indigo-500 rounded-full font-semibold cursor-pointer hover:text-white hover:bg-indigo-500"><%= link_to(tag.tag_name, tag_courts_path(tag_id: tag.id), {class: "hover:text-white"})  %><%= "#{tag.courts.count}" %></span>
      <% end %>
    <% end %>
  </div>
  <div class="mt-3">
    <%= form_with url: search_path, :method => 'get' do |f| %>

      <%= f.text_field :location, placeholder: "住所や行きたい場所を入力してください。", class: "bg-gray-200 mr-2 hover:bg-white hover:border-gray-300 focus:outline-none focus:bg-white focus:shadow-outline focus:border-gray-300 w-1/3 h-10" %>
      <%= f.select :keyword, [
        ['距離が近い順', 'near'],
        ['１時間当たりのコート料金が安い順', 'inexpensive'],
        ['コート数が多い順', 'number']
      ], {}, {class: 'bg-gray-200 hover:bg-white mr-2 hover:border-gray-300 focus:outline-none focus:bg-white focus:shadow-outline focus:border-gray-300 w-1/4 h-10'} %>
      <%= f.submit '検索', class: "bg-red-100 hover:bg-red-200 hover:border-gray-300 w-1/12 h-10 font-bold" %>
    <% end %>
    <button id="get_current_spot" type="button" class="mt-3 bg-green-300 font-bold hover:bg-white hover:text-green w-24 h-10">現在地取得</button>
  </div>
</div>
<div class="text-center">
  <h1 class="text-2xl sm:text-3xl text-center my-10">検索結果<br><span class="text-lg sm:text-2xl border-b-2 border-black">(検索ワードの地点から半径10km以内を表示)</span></h1>
</div>

<script>
  function geoFindMe() {
    function success(position) {
      const latitude  = position.coords.latitude;
      const longitude = position.coords.longitude;
      document.getElementById('location').value = `${latitude},${longitude}`;
    }

    function error() {
      alert('エラーが発生しました。')
    }

    if(!navigator.geolocation) {
       alert('Geolocation is not supported by your browser');
    } else {
      navigator.geolocation.getCurrentPosition(success, error);
    }
  }

  document.querySelector('#get_current_spot').addEventListener('click', geoFindMe);
</script>

app/views/courts/edit.html.erb
<% provide(:button_text, 'コート情報変更') %>
<div class="container py-4">
  <div class="py-2 user-form mx-auto  border-2 bg-white shadow-md">
    <h1 class="text-2xl sm:text-3xl text-center py-4 font-bold">コート情報編集</h1>
    <div class="form-wide mx-auto">
      <%= render 'form' %>
      <% if logged_in? && (current_user.id == @court.user.id or current_user.admin) %>
        <div class="text-center my-2">
          <%= link_to @court, method: :delete, data: { confirm: "削除してもよろしいですか?" } do %>
            <p class="inline-block text-red-500 bg-gray-100 border-2 hover:text-gray-100 hover:bg-red-500 hover:shadow font-base px-4 py-2 rounded text-base">コート情報削除</p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/courts/index.html.erb
<%= render 'courts/search_form' %>
<div class="container py-4 ">
  <h2 class="text-2xl text-center font-bold mb-4">お気に入り数が多いコート</h2>
  <% if @all_ranks.present? %>
    <ul class="mb-2 mx-auto grid gap-x-2 gap-y-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">  
      <% @all_ranks.each do |court| %>
        <%= render court %>
      <% end %>   
    </ul>
  <% else %>
    <div class="text-center">
      <p class="text-lg sm:text-2xl ">該当するコートはありません。</p>
    </div>
  <% end %>
</div>
<div class="container py-4">
  <h2 class="text-2xl text-center font-bold mb-4">最近投稿されたコート</h2>
  <% if @latest_courts.present? %>
    <ul class="mb-2 mx-auto grid gap-x-2 gap-y-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">    
      <% @latest_courts.each do |court| %>
        <%= render court %>
      <% end %>
    </ul>
  <% else %>
    <div class="text-center">
      <p class="text-lg sm:text-2xl ">該当するコートはありません。</p>
    </div>
  <% end %>
</div>

app/views/courts/new.html.erb
<% provide(:button_text, 'コート情報を投稿する') %>
<div class="container py-4">
  <div class="py-2 user-form mx-auto  border-2 bg-white shadow-md">
    <h1 class="text-2xl sm:text-3xl text-center py-4 font-bold">コート投稿</h1>
    <div class="form-wide mx-auto">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/courts/search.html.erb
<%= render 'courts/search_form' %>
<div class="container py-4 ">
  <ul class="mb-2 mx-auto grid gap-x-2 gap-y-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% @courts.each do |court| %>
      <%= render court %>
    <% end %>
  </ul>
  <%= paginate @courts %>
</div>

app/views/courts/show.html.erb
<div class="container">
  <div class="text-center">
    <h1 class="text-3xl sm:text-4xl text-center py-4">施設情報</h1>
  </div>
  <div class="grid sm:grid-cols-2 gap-6 mt-4">
    <div class="col-span-1">
      <div class="mt-2">
        <h2 class="font-bold mb-2 text-4xl"><%= @court.name %></h2>
        <% if @court_tags.any? %>
          <span>タグ:</span>
          <% @court_tags.each do |tag| %>
            <span class="inline-block my-2 px-3 py-1 border-2 border-indigo-500 rounded-full font-semibold cursor-pointer hover:text-white hover:bg-indigo-500"><%= link_to(tag.tag_name, tag_courts_path(tag_id: tag.id), {class: "hover:text-white"})  %></span>
          <% end %>
        <% end %>
      </div>
      <div class="mb-4">
        <p>ユーザー：<span><%= link_to @court.user.name, user_path(@court.user), class: "hover:underline" %></span></p>
      </div>
      <div class="flex mb-2">
        <div class='flex star-btn mt-1 mr-2 border-2 border-yellow-400 bg-red-100 hover:bg-white rounded' id="favorite_<%= @court.id %>">
          <%= render "favorites/favorite", court: @court %>
        </div>
        <% if logged_in? && (current_user.id == @court.user.id or current_user.admin) %>
          <%= link_to "コート情報変更", edit_court_path(@court), class: "inline-block text-gray-100 bg-green-500 border border-yellow-500 hover:text-green-500 hover:bg-white font-base px-4 py-2 rounded text-base" %>
        <% end %>
      </div>
      <% if @court.image? %>
        <%= link_to image_tag(@court.image.url), @court, size: '1000x1000', class: 'border-2' %>
      <% else %>
        <%= link_to image_tag(asset_path("default_court.png")), @court, size: '1000x1000', class: 'border-2' %>
      <% end %>
      <div class="text-center my-2">
        <%= link_to '予約サイトへGo!', "#{@court.reserve}", class: "inline-block text-gray-100 bg-pink-500 border border-yellow-500 hover:text-pink-500 hover:bg-white font-base px-4 py-2 rounded text-base" %>
      </div>
    </div>
    <div class="col-span-1 my-auto">
      <h2 class="text-center font-bold mb-2 text-2xl xl:text-3xl">コート情報</h2>
      <table class="border-2 shadow-md bg-white mx-auto text-sm md:text-lg lg:text-xl xl:text-2xl">
        <tr class="border-2">
          <th class="py-2 font-bold border-r-2">料金</th>  <th class="pl-2"><%= @court.price %>円/1時間</th>
        </tr>
        <tr class="border-2">
          <th class="py-2 font-bold border-r-2">コート数</th><th class="pl-2"><%= @court.number %>面</th>
        </tr>
        <tr class="border-2">
          <th class="py-2 font-bold border-r-2">住所</th><th class="pl-2"><%= @court.address %></th>
        </tr>
        <tr class="border-2">
          <th class="py-2 font-bold border-r-2">目的地まで</th>
          <% if logged_in? %>
            <th>
              <button class="button"><a href="https://www.google.com/maps/search/?api=1&query=<%= @court.latitude %>,<%= @court.longitude %> " class="font-bold pl-2 underline text-red-400">GoogleMapでルートを検索</a></button>
            </th>
          <% end %>
        </tr>
        <tr class="border-2">
          <th class="py-2 font-bold border-r-2">マップ確認</th>
          <th id="map"></th>
        </tr>
        <tr class="border-2">
          <th class="py-2 font-bold border-r-2">備考</th>
          <% if @court.remarks.present? %>
            <th class="pl-2"><%= @court.remarks %></th>
          <% else %>
            <th class="pl-2">記載なし</th>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="container py-2">
  <div class="col-md-8 mx-auto">
    <h3 class="font-bold text-xl mb-2">コメント： <%= @court.comments.count %>件</h3>
    <% if logged_in? %>
      <%= render 'shared/comment_form' %>
    <% else %>
      <h4>ログイン後、コメント可能になります。</h4>
    <% end %>
    <% if @court.comments.any? %>
      <ol class="microposts">
        <%= render @comments %>
      </ol>
      <%= paginate @comments %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  function initMap() {
    var test ={lat: <%= @court.latitude %>, lng: <%= @court.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @court.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }
</script>

<style type="text/css">
  #map { height: 200px;
        width: 70%;}
</style>

app/views/courts/tagsearch.html.erb
<%= render 'courts/search_form' %>
<div class="container py-4 ">
  <ul class="mb-2 mx-auto grid gap-x-2 gap-y-4 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
    <% if @tag_court_lists.any? %>
      <% @tag_court_lists.each do |court| %>
        <%= render court %>
      <% end %>
    <% end %>
  </ul>
  <%= paginate @tag_court_lists %>
</div>