config/routes.rb
Rails.application.routes.draw do
  root 'courts#index'
  get '/search', to: 'courts#search'
  get '/user_create', to: 'users#new'
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :courts
  get '/court_create', to: 'courts#new'
  post '/courts', to: 'courts#create'
  post '/guest_login', to: 'guest_sessions#create'
  resources :contacts
  resources :courts do
    resources :comments, only: %i[create destroy]
    resources :favorites, only: %i[create destroy]
  end
  resources :tags do
    get 'courts', to: 'courts#tagsearch'
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :follow_relationships, only: %i[create destroy]

  namespace :api, { format: 'json' } do
    namespace :v1 do
      get '/login', to: 'sessions#new'
      post '/login', to: 'sessions#create'
      delete '/logout', to: 'sessions#destroy'
      get '/user_create', to: 'users#new'
      get '/favorite_court/:id', to: 'users#favorite_court'
      get '/post_court/:id', to: 'users#post_court'
      get '/court_count/:id', to: 'users#court_count'
      # get '/courts/search/:location/:keyword', to: 'courts#search'
      get '/courts/search/:location', to: 'courts#search'
      resources :users
      resources :courts
      get '/court_create', to: 'courts#new'
      post '/courts', to: 'courts#create'
      get '/contact_create', to: 'contacts#new'
      post '/contacts', to: 'contacts#create'
      get '/taglist', to: 'courts#taglist'
      get '/court_rank', to: 'courts#court_rank'
      get '/latest_court', to: 'courts#latest_court'
      get '/court_tag/:id', to: 'courts#court_tag'
      get '/favorite_count/:id', to: 'favorites#favorite_count'
      get '/tagsearch/:id', to: 'courts#tagsearch'
      get '/comment_count/:id', to: 'comments#comment_count'
      get '/court_comment/:id', to: 'courts#court_comment'
      delete '/court/:court_id/user/:user_id/favorite', to: 'favorites#destroy'
      delete '/court/:court_id/user/:user_id/comment', to: 'comments#destroy'
      get '/court/:court_id/user/:user_id/favorite', to: 'favorites#show'
      get '/follower/:follower_id/following/:following_id/follow', to: 'follow_relationships#show'
      delete '/follower/:follower_id/following/:following_id/unfollow', to: 'follow_relationships#destroy'
      get '/follow_count/:id', to: 'follow_relationships#follow_count'
      get '/follower_count/:id', to: 'follow_relationships#follower_count'
      resources :courts do
        resources :comments, only: %i[create destroy]
        resources :favorites, only: %i[create]
      end
      resources :contacts
      resources :follow_relationships, only: %i[create]
      resources :users do
        member do
          get :following, :followers
        end
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="bg-white mb-3 h-20">
  <div class="text-center text-gray-500">
    <p>Copyright © 2021 Tennis court search All Rights Reserved.</p>
  </div>
  <nav class="float-right">
    <%= link_to "お問い合わせ", new_contact_path, class: "p-4 fs-3 text-dark" %>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="bg-green-100">
  <div class="container py-1">
    <div class="mx-auto">
      <div class="text-center mb-3 md:mb-0  lg:flex">
        <%= link_to "Tennis court search", root_path, class: "my-auto fs-1 text-info title-font" %>
        <nav class="mt-3 text-xs sm:text-xl md:text-2xl">
          <%= link_to "ホーム", root_path, class: "ml-2 m-2 hover:text-blue-400" %>
          <% if logged_in? %>
            <%= link_to "マイページ", current_user, class: "m-1 hover:text-blue-400" %>
            <%= link_to "コート投稿", new_court_path, class: "m-1 hover:text-blue-400" %>
            <%= link_to "ユーザー一覧", users_path, class: "m-1 hover:text-blue-400" %>
            <%= link_to "ログアウト", logout_path, method: :delete, class: "m-1 hover:text-blue-400" %>
          <% else %>
            <%= link_to "ゲストログイン", guest_login_path, method: :post, class: "m-1 hover:text-blue-400" %>
            <%= link_to "ログイン", login_path, class: "m-1 hover:text-blue-400" %>
            <%= link_to "新規登録", user_create_path, class: "m-1 hover:text-blue-400" %>
          <% end %>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>テニスコートサーチ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= javascript_pack_tag 'hello_vue' %>
    <%= stylesheet_pack_tag 'hello_vue' %>
  </body>
</html>